# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: cloudflared-secret
stringData:
  TUNNEL_ID: ENC[AES256_GCM,data:9HZATbz3o14zFeY86ckpXnSeOjQE6+JAC3/3C3rqg2Sn20DP,iv:kxEgW1bPzR24kjbUXsZH9GhjL9sNlKHAk7REFIEzo70=,tag:32Eez+Z5gE+eCIyAodecTw==,type:str]
  credentials.json: ENC[AES256_GCM,data:KA6YUXEObjh2ROqLTj1Pqs4VjFdcGf2nuqQOJOV/Ah78fHER800a4W7NqwYx6GP3PRpSKlTDfaeqzuWJc0M9DxwkC3MDly5KSqdEz8QfxfMUGV5XhV++dPBTrRzwn+itM5SN8XakuN56+RKRBk2SO21mJLknNw3uhw+62/vzaOAQ3HLGMFHeODMPjYtb2l+PVqUPUlD+MWPfmRiV38HcvayuedLnE4nXqc27jQbeBA==,iv:kNfZS5hPcG8W5As9u0UlOUQKRVoRAGFt80esEuaFuiM=,tag:m34HDc3jLnPNiKoWDKi05g==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age10r0snlfd4d6f7f8l2k0rx924pcm899vswtgfz2jgj3lf0wunngnqanwwf7
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB2ZXFJdDZwZlQwVTFFZlBQ
        L1BzMjkvdUt0YnkrNW9TWVp1Q3hpS2sra1I0CjdMWjlKcXRwRStVMWs1TWRoRHAz
        VHM2eTgvQzhQNER3dDBNeUxmSWg0K28KLS0tIHhOMjFSV3BBN1hQWW11Q0NwZG1C
        TXUxV0owWFZZMmk3S21GUWFncmNGcWsKjzJaimzchy6KbXVUiEnyt3GJoX7Ixbrj
        TAXOb1hu010auYYOyVbMd69yv2mH3CyWwj2Pp3gsJ3l1oY8a+xtMzg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-02-02T17:33:44Z"
  mac: ENC[AES256_GCM,data:shufEDlXGpEubrVeZq+daGAcOutri8Bm59AtQ6d1AyYUF7efd1SdK3sBHZeAhZerfL9URijod2a79o+f2BXnTIJy5TpQjxyRESlShe333QnMJ9jXk53ueMKg69aw77PymRr4kMibJpzVgDOplRZG3imV6HD+kESwgl5pgSPUIM0=,iv:MosmpRpNa1Vo1byAa4veaFCQxu9pH0mBSLBW9+ZDK/s=,tag:c4eO/mZzRdiyU2e/pY8FyA==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.9.4
