# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: cluster-secrets
  namespace: flux-system
stringData:
  SECRET_DOMAIN: ENC[AES256_GCM,data:EQZLBJexuk/VmWPM,iv:v1uYAIniAsSxZrm5KpRXu9oodALlgZzepnMxXtmKids=,tag:iWaQfA3SJYj2xM81sd7LWQ==,type:str]
  SECRET_CLOUDFLARE_TUNNEL_ID: ENC[AES256_GCM,data:+0FPCdZ9Xcs1vwE+sbo3tspiG1iBQB+o3n2kicO0ZcnI4qcT,iv:onFDlfvo/araB7EVD3LinWsbA0I5+LoBdDXXE21e/7Y=,tag:gi+Mrw7Gtmc3/HkHDjviHg==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age10r0snlfd4d6f7f8l2k0rx924pcm899vswtgfz2jgj3lf0wunngnqanwwf7
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBuVTVxR3N5WWdNNEZGSWIr
        eXgrd0RycVIrdGlpa1V1VmI3dU5hNzg3R0VvCnFMZ2hCY0d1Z21BVlRTT3BPNUNN
        cmgrdndieHVjZklqUlpDN0sxT2dudXMKLS0tIHdmMTRadlkyTUNHRWcxc0RlMW1M
        U0lPdHRhdFRqMHpnM0lTSmhleHhWZTQKkB9gJAX2sPdbISZlkUVRXJBRkVTUdA/M
        YANrw3nOFdti6NKO3v1x1hqlhdPGmDJ7GutFaGZdzsgDr3wek5eVxg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-02-02T17:20:28Z"
  mac: ENC[AES256_GCM,data:mWVwwOo7x6NvDLuy8fbIcfsz5lwN65YBsOCT83zgQ8FwFQe9LBPp+OhNPO2cDRq92kqwPCJNumnpZgXdBwxvPjy/ssCNpYOtnzuxCtdkmAiM+P1RNuGha/u/JN2dFPOL5vLC/yPFjTp5HH0fZuQBW5PPekfiOGOur88f5udmz1U=,iv:TT2ImYM0GplGiBYfirVTVupRW/JLPleW3wJBD7I1P9o=,tag:LOG9rw/rGdYgPijY17UG2g==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.9.4
